/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";

export default function Model({ pos, tree }) {
  const group = useRef();
  const { nodes, materials } = tree;
  return (
    <group ref={group} position={pos} dispose={null}>
      <mesh
        geometry={nodes.tree.geometry}
        material={materials["Material_1019.001"]}
        rotation={[-1.54, 0, 0]}
        scale={Math.random() + 0.7}
      />
    </group>
  );
}
