/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Rzyas (https://sketchfab.com/rzyas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/squid-game-giant-doll-7afd49dd07714651a6afa1fc4aac8576
title: Squid Game - Giant Doll
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";

export default function Model(props: any) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/scene.gltf") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (nodes.squidGameDoll_01_leher_squidGameDoll_01_MAT_0 as any)
                  .geometry
              }
              material={
                (nodes.squidGameDoll_01_leher_squidGameDoll_01_MAT_0 as any)
                  .material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (nodes.squidGameDoll_02_mata_squidGameDoll_02_MAT_0 as any)
                  .geometry
              }
              material={
                (nodes.squidGameDoll_02_mata_squidGameDoll_02_MAT_0 as any)
                  .material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (nodes.squidGameDoll_01_rambut_squidGameDoll_01_MAT_0 as any)
                  .geometry
              }
              material={
                (nodes.squidGameDoll_01_rambut_squidGameDoll_01_MAT_0 as any)
                  .material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (
                  nodes.squidGameDoll_01_bajuDanKaki_squidGameDoll_01_MAT_0 as any
                ).geometry
              }
              material={
                (
                  nodes.squidGameDoll_01_bajuDanKaki_squidGameDoll_01_MAT_0 as any
                ).material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (nodes.squidGameDoll_02_kepala_squidGameDoll_02_MAT_0 as any)
                  .geometry
              }
              material={
                (nodes.squidGameDoll_02_kepala_squidGameDoll_02_MAT_0 as any)
                  .material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (nodes.squidGameDoll_01_tangan_squidGameDoll_01_MAT_0 as any)
                  .geometry
              }
              material={
                (nodes.squidGameDoll_01_tangan_squidGameDoll_01_MAT_0 as any)
                  .material
              }
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={
                (nodes.squidGameDoll_02_jepit_squidGameDoll_02_MAT_0 as any)
                  .geometry
              }
              material={
                (nodes.squidGameDoll_02_jepit_squidGameDoll_02_MAT_0 as any)
                  .material
              }
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
